from .forms import LoginForm
from .forms_subscribe import PatientSubscribeForm, DoctorSubscribeForm
from .forms_profile import PatientProfileForm, DoctorProfileForm
from .appointment_type_form import AppointmentTypeForm
from .appointment_creation_form import AppointmentCreationForm
from .location_form import LocationForm
from .work_place_form import WorkPlaceForm
from .first_subscription_form import DoctorFirstSubscribeForm, WorkPlaceCreationForm