from .workschedule import ApiWorkschedule
from .doctor_info import ApiDoctorInfo
from .get_availability import ApiGetAvailability
from .workschedule_remove import ApiWorkscheduleRemove
from .work_place import apiWorkPlace
from .appointment_type import ApiAppointmentType
from .appointment_type_add import apiAppointmentTypeAdd
from .appointment_type_remove import apiAppointmentTypeRemove
from .appointment_type_get import apiAppointmentTypeGet
from .search import ApiSearch
from .patient_info import ApiPatientInfo
from .search_patient import apiSearchPatient
from .doctor_group_info import ApiDoctorGroupInfo