from .appointments_make_patient import apiAppointmentsMakePatient
from .appointments_make_doctor import apiAppointmentsMakeDoctor
from .appointments_cancel import apiAppointmentsCancel
from .appointments_get import apiAppointmentsGet
