from .appointment import Appointment
from .appointment_type import AppointmentType
from .available_slot import AvailableSlot
from .doctor import Doctor
from .doctor_group import DoctorGroup
from .location import Location
from .my_user import MyUser
from .patient import Patient
from .speciality import Speciality
from .work_place import WorkPlace
from .work_schedule import WorkSchedule